review of windspeed.py
umr-lops/xsarsea pull request #67
Opened 2024-05-16 15:03 UTC by vincelhx

2024-05-16 15:09 UTC, vincelhx commented
The first commint concerns cases where sigma0 <=0 or sigma0 == NaN (on the left side of the image here)

![nrcs_copol](https://github.com/umr-lops/xsarsea/assets/38355798/5389a5c2-ed62-42ab-9a22-cffc5d32b973)
before commit : 
![wspd_co_before](https://github.com/umr-lops/xsarsea/assets/38355798/fb5b49de-c217-4250-8079-cf6404986352)
after commit : 
![wspd_co_after](https://github.com/umr-lops/xsarsea/assets/38355798/898645f9-6df6-4be5-ba29-fce317b7f304)

In this case in the previous version, xsarsea was replacing copol by ancillary and used ancillary for dualpol inversion. Now inversion returns NaN

2024-05-27 13:49 UTC, vincelhx commented
the second change concerns the wind direction output from inversion. The returned angle was false before these commits. Now, the return complex can be used. 

use this formula to get wind direction in meteorological convention : 
`90 - (np.angle(-np.conj(wind_xsarsea), deg=True)) + xr_dataset.ground_heading) % 360`

2024-05-27 13:51 UTC, vincelhx commented
Lut being symetrical, i chose phi or -phi by taking the closest angle from ancillary.

2024-05-27 13:58 UTC, vincelhx commented
i also updated documentation. make html is ok @agrouaze

2024-05-27 14:37 UTC, agrouaze approved these changes

2024-05-29 09:03 UTC, vincelhx commented
added cmod7 gmf

2024-05-29 09:16 UTC, agrouaze requested changes
just the notebook windspeed_inversion to check .

2024-05-29 09:16 UTC, agrouaze commented on docs/examples/windspeed_inversion.ipynb
Can you check this notebook is output free?

2024-05-29 09:16 UTC, agrouaze commented on src/xsarsea/windspeed/other_luts.py
name of the script other_luts.py is a bit weird but you are the one that play the more with this lib.

2024-05-29 09:25 UTC, agrouaze approved these changes

2024-05-29 09:46 UTC, vincelhx commented on docs/examples/windspeed_inversion.ipynb
done

2024-05-29 09:47 UTC, merged